@startuml
|Робітник|
start
:Створює issues;
:Ставить тему;

|Система|
:Додає issues;

|Робітник|
:Обговорює завдання;

|Система|
:Оновлює стан;

|Робітник|
:Завершує Обговорення;

|Система|
:Закриває тему;

|Робітник|
stop

right footer
Організація баз даних.
