@startuml
|Робітник|
start
:Створює milestone;
:Ставить дату виконання;

|Система|
:Додає задачу;

|Робітник|
:Виконує завдання;

|Система|
:Оновлює стан задачі;

|Робітник|
:Завершує завдання;
:Закриває milestone;
stop

right footer
Організація баз даних.
НТУУ "КПІ ім.І.Сікорського"
Київ 2020 
end footer
@enduml
